In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

##Introduction to Tensors
In machine learning, tensors can be simply understood as n-dimensional array of numbers. However, from a intituive point of view, Tensor is a geometric object whose components transform in a specific way when coordinates change(we dont really need this).

So, tensor is a mathematical object that generalizes scalars(0D), vectors(1D), and matrix(2D) to potentially higher dimenstions.

In pytorch, tensors are initialized using torch.tensor(item_list).

torch.tensor.item() will get a python number from a tensor containing a single value.



In [ ]:
#scalar
scalar = torch.tensor(7)
#vector
vector = torch.tensor([6, 7, 8])
#matrix
MATRIX = torch.tensor([[5, 7, 6],
                       [8, 9, 10]])

In [ ]:
scalar

tensor(7)

In [ ]:
vector

tensor([6, 7, 8])

In [ ]:
MATRIX

tensor([[ 5,  7,  6],
        [ 8,  9, 10]])

In [ ]:

MATRIX.shape

torch.Size([2, 3])

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3, 4, 5],
                        [6, 7, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR2 = torch.tensor([[[[1,2,3],
                          [4,5,6],
                          [7,8,9]]]])
TENSOR2.ndim

4

In [ ]:
TENSOR2.shape

torch.Size([1, 1, 3, 3])

#About .shape()

.shape will return the dimensions of the tensor as a torch.size object.

Its important to note that each value given by .shape corresponds to some information about the data.

Example of 1 1 3 3, it could represent:
1 - batch _size
1 - channels
3 - height
3 - width
for a single greyscale image

### RANDOM TENSORS
Hard coding tensors is obviously very tedious and unnecessary. So, we use random tensors.

Random tensors are an important concpet in ML, as Nerual Networks learn through these random tensors.

Start with random tensors -> Look at Data -> Update Random tensrs -> Look at data -> ...

In [ ]:
##Creatig random tensors : torch.rand(shape / size)
random_tensor = torch.rand(3, 5, 6)
random_tensor

tensor([[[0.3641, 0.5104, 0.5391, 0.5434, 0.3794, 0.1116],
         [0.1277, 0.5011, 0.5600, 0.1224, 0.4345, 0.8295],
         [0.0709, 0.5439, 0.3699, 0.3350, 0.4466, 0.2937],
         [0.9434, 0.3208, 0.9760, 0.9586, 0.7291, 0.7377],
         [0.1963, 0.1808, 0.3679, 0.7474, 0.1494, 0.1272]],

        [[0.4252, 0.0913, 0.6690, 0.1297, 0.1194, 0.8262],
         [0.3151, 0.5840, 0.0785, 0.8009, 0.3300, 0.0654],
         [0.5899, 0.2122, 0.3646, 0.9205, 0.1153, 0.2387],
         [0.5192, 0.9921, 0.7925, 0.8191, 0.1095, 0.9663],
         [0.4660, 0.8138, 0.5135, 0.3319, 0.1694, 0.6513]],

        [[0.1070, 0.0920, 0.4853, 0.8574, 0.0470, 0.2804],
         [0.5763, 0.4359, 0.3685, 0.6759, 0.2222, 0.6720],
         [0.1744, 0.4807, 0.5226, 0.1984, 0.4549, 0.9915],
         [0.5192, 0.2988, 0.1873, 0.9206, 0.4993, 0.0581],
         [0.6880, 0.5053, 0.3974, 0.4616, 0.7570, 0.0208]]])

In [ ]:
"""For example: A random tensor to represent an image might be (color channels,
height, width) """
random_image_tensor = torch.rand(3, 224, 224)
random_image_tensor.shape

torch.Size([3, 224, 224])

###ZEROS AND ONE TENSORS
- Another common way we will see tensors is through zero tensors and one tensors.
- They are used as MASKS to decide which parts of the data the neural netowork
should ignore (through 0 tensors) or consider (through 1 tensors).
- If we want to amplify some part of the data, value greater than ones should be used.
- We can also get range of tensors using the arange function which works similary to the range function of python.

In [ ]:
zeroes = torch.zeros(1,3,4)
zeroes

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
ones = torch.ones(6, 7)
ones

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
#range of function using .arange(start, end, step) funciton
range = torch.arange(10, 20, 2.5)
range

tensor([10.0000, 12.5000, 15.0000, 17.5000])

###TENSOR DATATYPES
Tensor data types are important because for computation of two tensors, we need them to be of the same type.

**NOTE:** In pytorch and DL, we will run into three common errors:
1. Tensors not in right datatype.
2. Tensors not on same device. (cuda, cpu(default), or tpu).
3. Tensors not of the same shape.

By default, tensors are of float_32 datatype. float_16 is another common one.

In this sense, 'dype', 'device', and 'require_grad'(tracks gradient) are the three big parameters for tensor function.

In [ ]:
#float_32 tensor
float32 = torch.rand(3, 4, dtype = None, device = 'cpu', requires_grad=False)
float32

tensor([[0.4067, 0.7789, 0.6306, 0.3929],
        [0.3572, 0.4470, 0.2794, 0.6030],
        [0.0812, 0.1039, 0.0808, 0.6677]])

In [ ]:
#to float 16
float16 = float32.type(torch.float16)
float16

tensor([[0.4067, 0.7788, 0.6304, 0.3928],
        [0.3572, 0.4470, 0.2793, 0.6030],
        [0.0812, 0.1039, 0.0807, 0.6675]], dtype=torch.float16)

###MANIPULATING TENSORS
We know that Neural Networks learn by modifying the starting tensor according to the data. It does that by using various operations:

1. Additon
2. Subtraction
3. Multiplication (Element wise)
4. Division
5. Matrix Multiplication

The operations might include all of them or only some of them.

**Note:** Remember that tensors will not change unless the change is reassigned.

In [ ]:
some_tensor = torch.rand(3,4,5)
some_tensor

tensor([[[0.0365, 0.9597, 0.8497, 0.1444, 0.2766],
         [0.1523, 0.9360, 0.6128, 0.4409, 0.7586],
         [0.1198, 0.5468, 0.1549, 0.5261, 0.7774],
         [0.9012, 0.9536, 0.6713, 0.8577, 0.3243]],

        [[0.6949, 0.1410, 0.4747, 0.1984, 0.5771],
         [0.9515, 0.7148, 0.0902, 0.6193, 0.4777],
         [0.5970, 0.0953, 0.2373, 0.2156, 0.0596],
         [0.1811, 0.0882, 0.2927, 0.0758, 0.8037]],

        [[0.9396, 0.6111, 0.7639, 0.1885, 0.3012],
         [0.8682, 0.3760, 0.8517, 0.0679, 0.4158],
         [0.2638, 0.4046, 0.4818, 0.0652, 0.5095],
         [0.4536, 0.3449, 0.1763, 0.2374, 0.8269]]])

In [ ]:
some_tensor = some_tensor + 10
some_tensor

tensor([[[10.0365, 10.9597, 10.8497, 10.1444, 10.2766],
         [10.1523, 10.9360, 10.6128, 10.4409, 10.7586],
         [10.1198, 10.5468, 10.1549, 10.5261, 10.7774],
         [10.9012, 10.9536, 10.6713, 10.8577, 10.3243]],

        [[10.6949, 10.1410, 10.4747, 10.1984, 10.5771],
         [10.9515, 10.7148, 10.0902, 10.6193, 10.4777],
         [10.5970, 10.0953, 10.2373, 10.2156, 10.0596],
         [10.1811, 10.0882, 10.2927, 10.0758, 10.8037]],

        [[10.9396, 10.6111, 10.7639, 10.1885, 10.3012],
         [10.8682, 10.3760, 10.8517, 10.0679, 10.4158],
         [10.2638, 10.4046, 10.4818, 10.0652, 10.5095],
         [10.4536, 10.3449, 10.1763, 10.2374, 10.8269]]])

In [ ]:
some_tensor = some_tensor - 100
some_tensor

tensor([[[-89.9635, -89.0403, -89.1503, -89.8556, -89.7234],
         [-89.8477, -89.0640, -89.3872, -89.5591, -89.2414],
         [-89.8802, -89.4532, -89.8451, -89.4739, -89.2226],
         [-89.0988, -89.0464, -89.3287, -89.1423, -89.6757]],

        [[-89.3051, -89.8590, -89.5253, -89.8016, -89.4229],
         [-89.0485, -89.2852, -89.9098, -89.3807, -89.5223],
         [-89.4030, -89.9047, -89.7627, -89.7844, -89.9404],
         [-89.8189, -89.9118, -89.7073, -89.9242, -89.1963]],

        [[-89.0604, -89.3889, -89.2361, -89.8115, -89.6988],
         [-89.1318, -89.6240, -89.1483, -89.9321, -89.5842],
         [-89.7362, -89.5954, -89.5182, -89.9348, -89.4905],
         [-89.5464, -89.6551, -89.8237, -89.7626, -89.1731]]])

In [ ]:
some_tensor = some_tensor * -1
some_tensor

tensor([[[89.9635, 89.0403, 89.1503, 89.8556, 89.7234],
         [89.8477, 89.0640, 89.3872, 89.5591, 89.2414],
         [89.8802, 89.4532, 89.8451, 89.4739, 89.2226],
         [89.0988, 89.0464, 89.3287, 89.1423, 89.6757]],

        [[89.3051, 89.8590, 89.5253, 89.8016, 89.4229],
         [89.0485, 89.2852, 89.9098, 89.3807, 89.5223],
         [89.4030, 89.9047, 89.7627, 89.7844, 89.9404],
         [89.8189, 89.9118, 89.7073, 89.9242, 89.1963]],

        [[89.0604, 89.3889, 89.2361, 89.8115, 89.6988],
         [89.1318, 89.6240, 89.1483, 89.9321, 89.5842],
         [89.7362, 89.5954, 89.5182, 89.9348, 89.4905],
         [89.5464, 89.6551, 89.8237, 89.7626, 89.1731]]])

In [ ]:
some_tensor = some_tensor / 10
some_tensor

tensor([[[8.9963, 8.9040, 8.9150, 8.9856, 8.9723],
         [8.9848, 8.9064, 8.9387, 8.9559, 8.9241],
         [8.9880, 8.9453, 8.9845, 8.9474, 8.9223],
         [8.9099, 8.9046, 8.9329, 8.9142, 8.9676]],

        [[8.9305, 8.9859, 8.9525, 8.9802, 8.9423],
         [8.9048, 8.9285, 8.9910, 8.9381, 8.9522],
         [8.9403, 8.9905, 8.9763, 8.9784, 8.9940],
         [8.9819, 8.9912, 8.9707, 8.9924, 8.9196]],

        [[8.9060, 8.9389, 8.9236, 8.9812, 8.9699],
         [8.9132, 8.9624, 8.9148, 8.9932, 8.9584],
         [8.9736, 8.9595, 8.9518, 8.9935, 8.9490],
         [8.9546, 8.9655, 8.9824, 8.9763, 8.9173]]])

###MATRIX MULTIPLCATION
Matrix Multiplication is the most common tensor operation in DL and ML.
We know the rules for matrix multiplication and the resulting dimension of the tensor.

We do matrix multiplication using the **torch.matmul(tensos)** function given to us. It is recommended to use this, instead of either hard coding it or using the python built-in, @ symbol.

In [ ]:
multensor1 = torch.rand(3, 4)
multensor2 = torch.rand(4, 6)
print(multensor1)
print(multensor2)

tensor([[0.9080, 0.7290, 0.4839, 0.1067],
        [0.1866, 0.3879, 0.3820, 0.6606],
        [0.1970, 0.7484, 0.4621, 0.6539]])
tensor([[0.5504, 0.7098, 0.5996, 0.5617, 0.2564, 0.8705],
        [0.8272, 0.6350, 0.2469, 0.5250, 0.7140, 0.0083],
        [0.7604, 0.8803, 0.0282, 0.5532, 0.8182, 0.2465],
        [0.4560, 0.2102, 0.9985, 0.0981, 0.7109, 0.5074]])


In [ ]:
#Matrix Multiplication
result1 = torch.matmul(multensor1, multensor2)
result1

tensor([[1.5193, 1.5558, 0.8446, 1.1710, 1.2251, 0.9699],
        [1.0153, 0.8539, 0.8781, 0.5847, 1.1070, 0.5950],
        [1.3770, 1.1592, 0.9689, 0.8234, 1.4278, 0.6234]])

In [ ]:
#see the shape of the resulting tensor
result1.ndim, result1.shape

(2, torch.Size([3, 6]))

###Batch dimensions and Broadcasting
Rules differ as we multiply tensors with dimensions higher than 2.
The rules can be simplified as:
- Look at the last to dimensions of the tensor. Everything before them is treated as batch dimensions to be broadcasted.
- If the last two dimensions of the matrices follow the basic matrix multiplication of rule, the first check is completed.
- Then, we need to look at the batch dimensions. Check from right to left->If corresponding dimensions are equal or one of them is one then they can be broadcasted. The second check is complete.
- If the tensors follow the two checks then they can be multiplied.

**Note:** If there is a missing batch dimensions i.e., dimensions dont match then pytorch conceptually pads the missing batch dimensions with 1 to the left.

For example: If A(2,3,4) and B(4, 3) then we assume B as (1, 4, 3).

**Broadcasting**- It the pytorch's way of saying that it will automatically expand the smaller tensor if the dimensions follow the rules( 1 or equal).

In [ ]:
multensor3 = torch.rand(10, 20, 20, 30)
multensor4 = torch.rand(1, 20, 30, 50 )
result2 = torch.matmul(multensor3, multensor4)
result2.ndim, result2.shape

(4, torch.Size([10, 20, 20, 50]))

###DEALING WITH SHAPE ERRORS
We know that shape errors are very common in pytorch and DL. We can use transpose to alter some shapes of some valid tensors to change them into muplicable.

We can transpose a matrix using **torch.transpose(tensor, dim1, dim2)** or **tensor.T**.

In [ ]:
#multiplying these tensors will give us an error
#multensor5 = torch.rand(5 , 6)
#multensor6 = torch.rand( 5, 6)
#torch.mm(multensor5, multensor6)

In [ ]:
#so we can transpose one of the matrix to 6*5
multensor6= multensor6.T
result3 = torch.matmul(multensor5 , multensor6)
result3.ndim, result3.shape

(2, torch.Size([5, 5]))

###TENSOR AGGREGATION
Tensors can be aggregated to find the min, max, sum, avg values of the tensor.
We can also find the index at which the min or max values occur.

In [ ]:
new_tensor = torch.rand(3, 1024, 1024)
print(f"The minimum value: {new_tensor.min()}")
print(f"The maximum value: {new_tensor.max()}")
print(f"Max Index: {new_tensor.argmax()} And Min Index: {new_tensor.argmin()}")
print(f"Sum of Values: {new_tensor.sum()}")
print(f"Average: {new_tensor.mean()}")

The minimum value: 1.0728836059570312e-06
The maximum value: 0.9999999403953552
Max Index: 2000302 And Min Index: 1503178
Sum of Values: 1572169.875
Average: 0.4997793436050415


###RESHAPING, STACKING, SQUEEZING, UNSQUEEZING, AND PERMUTING TENSORS
As we have already mentioned several times, shape errors are among the most common errors we encounter in DL. To avoid this, we can reshape the tensor according to our need.

1. Reshape - Use torch.reshape(input, shape) to reshape input to shape. The shape must be valid according to the original shape of the tensor.
2. View - Use tensor.view(shape) to view the tensor in specified shape. View shares the same memory space as the original tensor, so changing the view changes the tensor.
3. Stack - Use torch.stack(tensors, dim) to stack tensors (concatenate) at the specified dimension
4. Squeeze - Use torch.squeeze(input) to remove all dimensions with value 1.
5. Unsqueeze - Use torch.unsqueeze(input, dim) to add 1 dimension at the specified dimension.
6. Permute - Returns a view of the original tensor with dimensions permuted in a certain order.

In [ ]:
original_tensor = torch.rand(1, 3, 4)
original_tensor

tensor([[[0.2266, 0.6373, 0.5396, 0.3764],
         [0.3351, 0.1968, 0.7151, 0.3411],
         [0.8958, 0.1002, 0.3590, 0.9578]]])

In [ ]:
reshaped_tensor = original_tensor.reshape(6, 2)
reshaped_tensor

tensor([[0.2266, 0.6373],
        [0.5396, 0.3764],
        [0.3351, 0.1968],
        [0.7151, 0.3411],
        [0.8958, 0.1002],
        [0.3590, 0.9578]])

In [ ]:
#Creating a view with another shape
view_tensor = reshaped_tensor.view(3, 4)
view_tensor

tensor([[0.2266, 0.6373, 0.5396, 0.3764],
        [0.3351, 0.1968, 0.7151, 0.3411],
        [0.8958, 0.1002, 0.3590, 0.9578]])

In [ ]:
#Stacking tensors upon tensors
stack_tensor = torch.rand(3, 4)
stacked_tensor = torch.stack([view_tensor, stack_tensor], dim = 1)
stacked_tensor

tensor([[[0.2266, 0.6373, 0.5396, 0.3764],
         [0.4929, 0.0859, 0.2941, 0.1581]],

        [[0.3351, 0.1968, 0.7151, 0.3411],
         [0.7547, 0.5282, 0.9566, 0.8661]],

        [[0.8958, 0.1002, 0.3590, 0.9578],
         [0.9805, 0.1889, 0.7284, 0.0815]]])

In [ ]:
image_tensor_permute = torch.rand(3, 244, 244)
permuted = image_tensor_permute.permute(1, 2, 0)
permuted.shape

torch.Size([244, 244, 3])

###REPRODUCIBILITY
Neural networks usually start with randomly initialized tensors (such as weights and biases). Since these tensors are random, training the same model multiple times can produce different results.

To make the random numbers reproducible, PyTorch provides the function:

- torch.manual_seed(seed)

          where seed is any integer.

Setting the same seed causes PyTorch's random number generator to produce the same sequence of random numbers every time the program is run. This means tensors created after setting the seed will have the same values across runs (provided the rest of the code is the same).
torch.manual_seed() does not remove randomness. It simply makes the randomness deterministic (repeatable).

You do not need to call torch.manual_seed() before every tensor.

- For example:

    import torch

    torch.manual_seed(42)

    A = torch.rand(2, 2)
    B = torch.rand(2, 2)
    C = torch.rand(2, 2)

Here, A, B, and C will always have the same values every time you run the program because they are generated from the same deterministic sequence.

You only need to call torch.manual_seed() again if you want to restart the random number sequence.

torch.manual_seed(42)
A = torch.rand(2, 2)

torch.manual_seed(42)
B = torch.rand(2, 2)

print(torch.equal(A, B))  # True

In [ ]:
RANDOM_SEED = 45
torch.manual_seed(RANDOM_SEED)
seed_tensor = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
seed_tensor2 = torch.rand(3, 4)

print(seed_tensor)
print(seed_tensor2)
print(seed_tensor == seed_tensor2)

tensor([[0.1869, 0.9613, 0.6834, 0.8988],
        [0.0505, 0.5555, 0.7861, 0.0566],
        [0.7842, 0.1480, 0.0388, 0.1037]])
tensor([[0.1869, 0.9613, 0.6834, 0.8988],
        [0.0505, 0.5555, 0.7861, 0.0566],
        [0.7842, 0.1480, 0.0388, 0.1037]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
